name: flutter_demo_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <=3.3.10"

dependencies:
  auto_route: ^7.2.0
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.2
  device_info_plus: ^9.0.1
  dio: ^5.1.2
  expandable: ^5.0.1
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.4
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.6
  freezed: ^2.0.3+1
  freezed_annotation: ^2.0.3
  google_sign_in: ^5.4.4
  hooks_riverpod: ^2.3.6
  intl: ^0.18.0
  json_annotation: ^4.7.0
  logger: ^1.1.0
  package_info_plus: ^4.0.1
  permission_handler: ^10.0.0
  persistent_bottom_nav_bar: ^5.0.2
  pull_to_refresh: ^2.0.0
  retrofit: ^4.0.1
  synchronized: ^3.0.0+2
  url_launcher: ^6.1.4
  uuid: ^3.0.6
#
#dependency_overrides:
#  analyzer: ">=4.3.1 <5.4.0"

dev_dependencies:
  auto_route_generator: ^7.1.1
  build_runner: ^2.1.11
  flutter_flavorizr: ^2.1.3
  flutter_gen_runner:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.4.4
  json_serializable: ^6.5.4
  retrofit_generator: ^7.0.1

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    dev:
      app:
        name: "Flutter App Demo Dev"
      android:
        applicationId: "com.flutter.demo.dev"
      ios:
        bundleId: "com.flutter.demo.dev"

    staging:
      app:
        name: "Flutter App Demo Stg"
      android:
        applicationId: "com.flutter.demo.stg"
      ios:
        bundleId: "com.flutter.demo.stg"

    production:
      app:
        name: "Flutter App Demo Pro"
      android:
        applicationId: "com.flutter.demo.pro"
      ios:
        bundleId: "com.flutter.demo.pro"

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true

flutter:
  uses-material-design: true

  fonts:
    - family: SFProTextRegular
      fonts:
        - asset: assets/fonts/SF-ProText-Regular.ttf

  assets:
    - assets/
